### ISSUE TITLE
WHERE is Midori Engine?

### ISSUE THREAD

**Issue by ifshizuku** [mieotoha/mieotoha#2]
Roadmap
August
˗ˋˏ ˎˊ˗

**Comment by mieotoha** [comment]
（やばい、忘れてた）
少し後ろに1年遅らせましょう
申し訳ありません！！！🙇🙇🙇

**Comment by mieotoha** [comment]
最近、三次元での多忙なスケジュールにより、多くの活動の中で取捨選択を余儀なくされていますが、残念なことに「Midori Engine」の開発活動もキャンセルに追い込まれており、この決断については、様々な形での告知が間に合わず申し訳ありませんでした

「Midori Engine」の開発活動を継続するタイミングについては、今後詳細な内容が各SNSに発表されるのでご期待ください。
